---
title: "Visualizing Compression Results"
author: "Petur Helgi Einarsson - phe1@hi.is"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE, message=FALSE}
knitr::opts_chunk$set(echo = FALSE, message=FALSE)
library(ggplot2)
library(readr)
library(dplyr)
library(tidyr)
library(see)
source("./helper_funcs.R")
```

We start by reading in the data and fitting linear models through the data points

```{r, echo=TRUE}
df <- read_csv("./supplementary_data.csv")

fit.compression <- lm(I(compressed / 2^30) ~ I(full_size / 2^30):res_type + 0, df)
fit.compression.time <- lm(compression_t ~ I(full_size / 2^20):res_type + 0, df)
fit.decompression.time <- lm(decompression_t ~ I(full_size / 2^20):res_type + 0, df)
```

We can then visualize the results along with the fitted lines.
```{r, echo=TRUE}

df <- df %>%
  cbind(
    compression.pred=predict(fit.compression),
    compress.time.pred=predict(fit.compression.time),
    decompress.time.pred=predict(fit.decompression.time)
  )

plt.compression <- do.plot(plot.compression, df)
plt.compress.time <- do.plot(plot.compression.time, df, ignore="gzip9")
plt.decompress.time <- do.plot(plot.decompression.time, df)
plt.ratio <- do.plot(plot.ratio, df)
plt.compression.speed <- do.plot(plot.compression.speed, df)
plt.decompression.speed <- do.plot(plot.decompression.speed, df)


# Display the plots
plt.compression + stat_smooth(method='lm', fullrange = T, size=0.5) + labs(title="Compression")
plt.compress.time + stat_smooth(method='lm', fullrange = F, size=0.5) + labs(title="Compression time")
plt.decompress.time + stat_smooth(method='lm', fullrange = T, size=0.5)+  labs(title="Decompression time")
plt.ratio + labs(title="Compression ratio")

# Display the speed of compression and decompression
plt.compression.speed + labs(title="Compression speed")
plt.decompression.speed + labs(title="Decompression speed")
```

```{r}
res <- cbind(
  get_slopes(fit.compression.time, "Compress.speed", invert=TRUE),
  get_slopes(fit.decompression.time, "Decompress.speed", invert=TRUE),
  get_slopes(fit.compression, 'Compression.ratio', invert=TRUE)
)

knitr::kable(res, digits=4, caption="Comparison of methods used. The speed columns are measured in MB/s.")
```

